### ISSUE TITLE
add topic special-functions

### ISSUE THREAD

**Issue by Beliavsky** [arjenmarkus/specfunc-fullerton#1]
I suggest adding the topic `special-functions` in the About section at https://github.com/arjenmarkus/specfunc-fullerton.

Thanks for the project, which I added to my list https://github.com/Beliavsky/Fortran-code-on-GitHub/blob/main/README.md .

John Burkhardt's Fortran 90 of Fullerton's library is at https://people.math.sc.edu/Burkardt/f_src/fn/fn.html .

**Comment by arjenmarkus** [comment]
Done, thanks for the suggestion. And the links!

Regards,

Arjen

Op di 10 mei 2022 om 17:55 schreef Beliavsky ***@***.***>:
