### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by Beliavsky** [arjenmarkus/specfunc-fullerton#2]
For "Library for evaluating special mathematical function" there should be an "s" at the end, and near the end "mahematical" should be "mathematical".

**Comment by arjenmarkus** [comment]
Gosh, I should have read that one a bit better too! I did carefully read my
PDF file on the library (doc directory) and found an embarrassingly large
number of typos and such. To be amended soon!

Regards,

Arjen

Op di 10 mei 2022 om 17:57 schreef Beliavsky ***@***.***>:

**Comment by arjenmarkus** [comment]
Done - the corrections were made some time ago, but I should have closed the issue.
